version: "3"
services:
  redis:
    container_name: exporter-redis-dev
    image: redis:4.0.1-alpine
    ports:
      - "6379:6379"
  test:
    container_name: exporter-dev
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    volumes:
      - ../../:/code/
    command: py.test -s --cov-report term --cov-report html
    depends_on:
      - redis
      - minio
    links:
      - redis
      - minio
    environment:
      - DJANGO_SETTINGS_MODULE=tests.settings
      - AWS_S3_ACCESS_KEY_ID=X0UPMLLFW54LALL86ND6
      - AWS_S3_SECRET_ACCESS_KEY=F3evyDre0kr4x4u8QFtR6iUmQc+0RVyB/m171TGI
      - AWS_S3_BUCKET_NAME=test-exporter
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_REGION_NAME=us-east-1
      - MINIO_ACCESS_KEY=X0UPMLLFW54LALL86ND6
      - MINIO_SECRET_KEY=F3evyDre0kr4x4u8QFtR6iUmQc+0RVyB/m171TGI
      - MINIO_HOST=http://minio:9000
  minio:
    container_name: exporter-minio-dev
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=X0UPMLLFW54LALL86ND6
      - MINIO_SECRET_KEY=F3evyDre0kr4x4u8QFtR6iUmQc+0RVyB/m171TGI
    ports:
      - "9000:9000"
    command: minio server /s3-folder
    volumes:
      - s3-folder:/s3-folder
volumes:
  s3-folder: